name: first workflow

on:
  push:
      branches: 
              - main

jobs:
  example-jobs:
          runs-on: ubuntu-latest
          steps:
              - name: print welcome message
                run: echo "Welcome to  our first workflow."
              - name: Checkout Repository
                uses: actions/checkout@v6.0.2
              - name: List Files
                run: ls -la 
